# https://taskfile.dev/usage/
version: '3'
tasks:
  default: mix format && mix test
  sh: mix format && iex --erl "-kernel shell_history enabled" -S mix
  run: iex --erl "-kernel shell_history enabled" -S mix phx.server
  fmt: mix format
  test-all: |
    mix test --include external
  
  users: |
    curl 'https://api.notion.com/v1/users' \
      -H 'Authorization: Bearer '"$NOTIONER_ACCESS_TOKEN"'' \
      -H "Notion-Version: 2022-06-28" | jq

  setup: |
    mix setup

